permalink: pretty

excerpt_separator: "<!--end excerpt-->"
paginate: 5
paginate_path: "/page/:num"

safe: true
lsi: false
highlighter: rouge
markdown: kramdown

root_url: /blog/
root_url_alt: /blog
static_url: /blog/static/
production_url : "http://siggame.io/blog/"

gems:
  - jekyll-paginate
